### ISSUE TITLE
How to run our own server ?

### ISSUE THREAD

**Issue by Aeris1One** [TheCodeCrafter/SpaceRPG#10]
Hi,
seems this project to be down, but I want to try it.
Can you tell me how to do ?

I did those steps and resulted in a blank page on myip:3000 :
```
git clone this-repo
cd SpaceRPG/root/
npm install
npm start server
```

Seems there is missing some assets, am i right ?

**Comment by noahcoetsee** [comment]
Yes this project was focused on documentation and creative design of the game, and we never reached the development phase.
